---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# txBenefit

<!-- badges: start -->
<!-- badges: end -->

This tutotial provides background information and stepwise tutorial for Cb calculations.

###What is Cb?

Consider a risk model that predicts the rate or risk of an outcome (e.g., 5-year mortality due to breast cancer). The risk model estimates the risk / rate of the event given an individual's characteristics. The discriminatory performance of such a model is often communicated in terms of C-statistic (or area under the curve of the receiver operating characteristic curve).

Often times, we are interested in using patient characteristics to decide whether a patient should receive treatment or not. Instead of a risk mode, in this circumstance we can develop a model directly predicting treatment benefit:

$$b=E(Y|X,A=1)-E(Y|X,A=0)$$
    
Cb is a threshold-free index that describes to what extent covariates X can discriminate among individuals who will differently benefit from treatment, given their covariates.

In a nutshell, Cb is conceptually equal to C-statistic for risk models.

If B1, B2, and B3 are random draws from the distibution of b (as defined in the above equation), then 

$$C_b=1-E(B_1)/E(max(B_2,B_3))$$

The table below compares and contrasts C and Cb statstics. 


| First Header  | C-statistic    | Cb                           |
| :------------ | :----------------------------------------:  | ----------------------------------:         |
| Application   | Models for risk| Models for treatment benefit |
| Probabilistic interpretation    | Randomly select a pair of individuals, one that experiences the outconme and one that does not. C is the probability that the risk model predicts a higher risk for the individual with event    | Randomly select a pair of individuals. Consider the two scenarios: A) give treatment to one at random, B) give treatment to the one with the higher predicted benefit. Cb is the relative loss of efficiency of  scenario A compared with scenario B               |
| Range     | [0.5,1]  | [0,1] |
| Interpretation     | The model with higher C is better  | The model with higher Cb is better |


## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("msadatsafavi/txBenefit")
```

##How the package works

The package provides simple functions for calculating Cb for different regression models. 


###Direct calculation of Cb when the vector of benefits are available.
Cb.simple() is for such an estimation method.

<<<<<<< HEAD
In the example below, we simply create vector B of randomly generated numbers.

```{R}
library(txBenefit)
B<-runif(100)
res<-Cb.simple(B)
print(res)
```

In effect, this function equals to creating all possible pairs within the vector B, and estimating the maximum within each pair.

Now let's focus on a more realistic example. The package comes with a simulated randomized clinical trial (RCT) data, named rct_data. 

```{R}
data("rct_data")
```

Let's take a look at the first few rows:

```{R echo=FALSE}
knitr::kable(rct_data[1:7,])
```

This is a hypothetical RCT of two treatments for Chronic Obstructive Pulmonary Disease (COPD). COPD is a chronic disease that comes with episodes of intensified activity, called exacerbations. The benefit of treatment is in reducing the rate of such exacerbations.

The columns are as follows:

tx: treatment assignement variable (0: placebo, 1: treatment)

female: 1 for female and 0 for male

age: age in years at time of randomization

prev_hosp: history of COPD-related hospitalization in the previous 12 months (a predictor of future exacerbation), 0: no history, 1: positive history

prev_ster: history of COPD-related hospitalization in the previous 12 months (a predictor of future exacerbation), 0: no history, 1: positive history

fev1: Forced expiratory volume at one second, a measure of lung capacity

sgrq: St. George Respiratory Questionnaire score: a measure of functional capacity in COPD

time: total follow-up time in years (maximum 1 year)

tte: time to first exacerbation in years (NA if no exacerbation)

n_exac: total number of exacerbations during follow-up


###Cb calculations for different regresion frameworks

The package comes with functions that help you calculate Cb for different type of regression models. These function accept a fitted regresion object and a few extra parameters and calculate Cb.

####Logistic regression
Imagine we want to evaluate the predictability of treatment benefit in terms of reducing 6-month exacerbation risk. because in the RCT, everyone is followed for at least 6 month, there is no censoring for this outcome, and logistic regresison is a valid framework for inference.

We first create a binary variable indicating whether an exacerbation occured within the first 6 months.
```{R}
rct_data[,'b_exac']<-rct_data[,'tte']<0.5
rct_data[which(is.na(rct_data[,'b_exac'])),'b_exac']<-FALSE
```

Now lets fit the regression 

```{R}
reg.logostic<-glm(formula = b_exac ~ tx + sgrq + prev_hosp + prev_ster + fev1, data = rct_data, family = binomial(link="logit"))

summary(reg.logostic)
```

Now we call the Cb.logistic funciton. This function has two mandatory parameters: the glm object containing the logit model, and a text variable indicating the name of treatment variable. 

```{R}
res.logistic<-Cb.logistic(reg.logostic,tx_var = "tx")
print(res.logistic)
```

The main outout is Cb.

Cb.logistic (and similar functions) calculate Cb parametrically. The package includes semi-parametric methods for Cb calculation as well. To use the semi-parametric method, we simply set the value of optinal parameter semi_parametric to TRUE.

```{R}
res.logistic.NP<-Cb.logistic(reg.logostic,tx_var = "tx",semi_parametric = T)
print(res.logistic.NP)
```


#####What happens under the hood?

Indeed, we can estimate the probability of outcome for each patient under each treatment allocation

```{R}
new_data0<-rct_data
new_data0[,'tx']<-0
new_data1<-rct_data
new_data1[,'tx']<-1
B<-predict.glm(reg.logostic, newdata=new_data0, type="response")-predict.glm(reg.logostic, newdata =new_data1, type="response")
hist(B)
Cb.simple(B)
```


###Cb.logistic() for Cb calculation based on a logit model
The above-mentioned calculations are already provided in the Cb.logistic function

```{R}
res.logistic<-Cb.logistic(reg.logostic,tx_var = "tx")
res.logistic
```

We can estimate Cb non-parametrically as well. 

```{R}
res.logistic.NP<-Cb.logistic(reg.logostic,tx_var = "tx",semi_parametric = T)
res.logistic.NP
plot(res.logistic.NP)
lines(res.logistic)
```


###Cb.poisson() for count models

First let's do this directly

```{R}
reg.poisson<-glm(formula = n_exac ~ tx + tx:sgrq + prev_hosp + prev_ster + fev1 + offset(log(time)), data = rct_data, family = poisson(link="log"))

summary(reg.poisson)

new_data0<-rct_data
new_data0[,'tx']<-0
new_data0[,'time']<-1
new_data1<-rct_data
new_data1[,'tx']<-1
new_data1[,'time']<-1

B<-predict.glm(reg.poisson, newdata=new_data0, type="response")-predict.glm(reg.poisson, newdata =new_data1, type="response")
hist(B)
Cb.simple(B)
```

Again, like in the case of Cb.logistic(), we have a shotcut function that does all these

```{R}
res.poisson<-Cb.poisson(reg.poisson,tx_var = "tx")
res.poisson
```



Important notes: Cb cannnot currently be calculated for Cox models that have time-dependent covariates, nor for the models with strata

